sudo: required

language: go

env:
    - GO111MODULE=on CI=on

go:
    - 1.13

before_install:
  # install inotifywait
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y inotify-tools

script:
    - go test -v -race -failfast --cover -covermode=atomic -mod=vendor -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
