sudo: required

language: go

env:
    - GO111MODULE=on

go:
    - 1.13

script:
    - go test -v -race -failfast --cover -covermode=atomic -mod=vendor -coverprofile=coverage.out

after_success:
    - bash <(curl -s https://codecov.io/bash)
