package main

type AutoGenerated struct {
	Path   string `json:"path"`
	Create []struct {
		HTTP    string `json:"http,omitempty"`
		URL     string `json:"url,omitempty"`
		Method  string `json:"method,omitempty"`
		Headers struct {
			Accept      string `json:"accept"`
			ContentType string `json:"content-type"`
		} `json:"headers,omitempty"`
		Action  string `json:"action,omitempty"`
		Command string `json:"command,omitempty"`
		A       string `json:"a,omitempty"`
		B       string `json:"b,omitempty"`
	} `json:"create"`
}
type config struct {
	Path string `yaml:"path"`
}
